Repository binance/binance-connector-node, pull requests merged in 2022-10, with the labels that each got.

#109 fix(savings): make asset optional param
  __tests__/spot/savings/savingsCustomizedPosition.test.js
  __tests__/spot/savings/savingsFlexibleProductPosition.test.js
  src/modules/savings.js
Labels: size/M

#110 v2.0.0-rc.2 Release
  CHANGELOG.md
  __tests__/spot/futures/futuresCollateralRepay.test.js
  __tests__/spot/futures/futuresCollateralRepayLimit.test.js
  __tests__/spot/futures/futuresCollateralRepayQuote.test.js
  __tests__/spot/futures/futuresCollateralRepayResult.test.js
  __tests__/spot/futures/futuresLoanAdjustCollateral.test.js
  __tests__/spot/futures/futuresLoanBorrow.test.js
  __tests__/spot/futures/futuresLoanCalcAdjustLevel.test.js
  __tests__/spot/futures/futuresLoanCalcMaxAdjustAmount.test.js
  __tests__/spot/futures/futuresLoanConfigs.test.js
  __tests__/spot/futures/futuresLoanRepay.test.js
  __tests__/spot/savings/savingsCustomizedPosition.test.js
  __tests__/spot/savings/savingsFlexibleProductPosition.test.js
  examples/spot/futures/futuresCollateralRepay.js
  examples/spot/futures/futuresCollateralRepayLimit.js
  examples/spot/futures/futuresCollateralRepayQuote.js
  examples/spot/futures/futuresCollateralRepayResult.js
  examples/spot/futures/futuresLoanAdjustCollateral.js
  examples/spot/futures/futuresLoanBorrow.js
  examples/spot/futures/futuresLoanCalcAdjustLevel.js
  examples/spot/futures/futuresLoanCalcMaxAdjustAmount.js
  examples/spot/futures/futuresLoanConfigs.js
  examples/spot/futures/futuresLoanRepay.js
  package-lock.json
  package.json
  src/modules/futures.js
  src/modules/savings.js
Labels: size/XL, lgtm, approved

#108 flow cicd support
  .cicd/publish.yml
Labels: size/XS

#111 Update combinedStreams.js
  examples/websocket/spot/combinedStreams.js
Labels: size/XS, Reviewing
